using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CubeGenerator : MonoBehaviour
{
    // №┐йL№┐й№┐й№┐й[№┐йu№┐й№┐йPrefab
    public GameObject cubePrefab;

    // №┐й№┐й№┐йнїv№┐й№┐й№┐йp№┐й╠Ћ¤љ№┐й
    private float delta = 0;

    // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠љ№┐й№┐й№┐й№┐йніu
    private float span = 1.0f;

    // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠љ№┐й№┐й№┐й№┐й╩њu№┐йFX№┐й№┐й№┐йW
    private float genPosX = 12;

    // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠љ№┐й№┐й№┐й№┐й╩њu№┐йI№┐йt№┐йZ№┐йb№┐йg
    private float offsetY = 0.3f;
    // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠Јc№┐й№┐й№┐й№┐й№┐й╠ініu
    private float spaceY = 6.9f;

    // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠љ№┐й№┐й№┐й№┐й╩њu№┐йI№┐йt№┐йZ№┐йb№┐йg
    // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠Ѕ№┐й№┐й№┐й№┐й№┐й№┐й╠ініu
    private float spaceX = 0.4f;

    // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠љ№┐й№┐й№┐й№┐й┬љ№┐й№┐й╠Ј№┐й№┐й
    private int maxBlockNum = 4;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        this.delta += Time.deltaTime;

        // span№┐йb№┐й╚Ј№┐й╠ј№┐й№┐йнѓ№┐й№┐йo№┐й▀ѓ№┐й№┐й№┐й№┐й№┐й№┐й­њ▓ѓОѓ№┐й
        if (this.delta > this.span)
        {
            this.delta = 0;
            // №┐й№┐й№┐й№┐й№┐й№┐й№┐й№┐йL№┐й№┐й№┐й[№┐йu№┐й№┐й№┐й№┐й№┐й№┐й№┐й№┐й№┐й_№┐й№┐й№┐й╔ї№┐й№┐й▀ѓ№┐й
            int n = Random.Range(1, maxBlockNum + 1);

            // №┐йw№┐йУѓх№┐й№┐й№┐й№┐й№┐й№┐й№┐й№┐й№┐йL№┐й№┐й№┐й[№┐йu№┐й­љХљ№┐й№┐й№┐й№┐й№┐й
            for (int i = 0; i < n; i++)
            {
                // №┐йL№┐й№┐й№┐й[№┐йu№┐й╠љ№┐й№┐й№┐й
                GameObject go = Instantiate(cubePrefab);
                go.transform.position = new Vector2(this.genPosX, this.offsetY + i * this.spaceY);
            }
            // №┐й№┐й№┐й╠ЃL№┐й№┐й№┐й[№┐йu№┐й▄ѓ┼ѓ╠љ№┐й№┐й№┐й№┐й№┐й№┐йнѓ№┐й№┐й№┐й№┐й▀ѓ№┐й
            this.span = this.offsetX + this.spaceX * n;
        }
    }
}
